---
# file: roles/common/tasks/main.yml
# This could be used to make sure resteasy is up to date.

# ntp example:
- name: Be sure ntp is installed
  apt: name=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: 
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

